[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pet_passport = "CxdvuzcrpqtJawZm8jDfKf7G92sQPehdtkrYdEoGzaTk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
